---
name: "PSSA"

on: [pull_request] #push

jobs:
  dependencies:
    name: "Install Dependencies"
    runs-on: ubuntu-latest
    steps:
    - name: "Install ScriptAnalyzer"
      shell: pwsh
      run: |
        Install-Module PSScriptAnalyzer
        
  pssa:
    name: "Run PSSA"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
    - uses: actions/checkout@v2
    - name: "Lint with ScriptAnalyzer"
      shell: pwsh
      run: |
        Invoke-ScriptAnalyzer -Path *.ps1 -Recurse -Outvariable issues
        $errors   = $issues.Where({$_.Severity -eq 'Error'})
        $warnings = $issues.Where({$_.Severity -eq 'Warning'})
        if ($errors) {
            Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
        } else {
            Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
        }
