---
name: "ScriptAnalyzer"

on: [pull_request] #push

jobs:
  job:
    name: "Run PSSA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ScriptAnalyzer
        shell: pwsh
        run: |
          # $VerbosePreference = "Continue"
          Install-Module PSScriptAnalyzer
          Invoke-ScriptAnalyzer -Path . -Recurse -Outvariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }
