---
name: "ScriptAnalyzer"

on: [pull_request] #push

jobs:
  job:
    name: "Run PSSA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ScriptAnalyzer
        shell: pwsh
        run: |
          # $VerbosePreference = "Continue"
          Install-Module PSScriptAnalyzer
          Invoke-ScriptAnalyzer -Path . -Recurse -ReportSummary
