---
name: "ScriptAnalyzer"

on: [pull_request] #push

jobs:
  job:
    name: "Run PSSA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ScriptAnalyzer
        shell: pwsh
        run: |
          $VerbosePreference = "Continue"
          Get-Location
          Install-Module PSScriptAnalyzer
          Invoke-ScriptAnalyzer -Path *.ps1 -Recurse
