---
name: "Default Workflow"

on: [pull_request] #push

jobs:
  job:
    name: "Job"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo
        shell: pwsh
        run: |
          echo PowerShellCore
