---
name: "Default Workflow"

on: push #workflow_dispatch # [pull_request] #push

jobs:
  job:
    name: "Job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo
        shell: pwsh
        run: |
          echo PowerShellCore
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
